[package]
name = "pinniped-proxy"
version = "0.1.0"
authors = [
    "Andres Martinez <andresmgot@vmware.com>",
    "Antonio Gamez <agamez@vmware.com>",
    "Michael Nelson <minelson@vmware.com>"
    ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
hyper = "0.13"
structopt = "0.3"
# Update to 0.3 once apparent issue with the nascent 0.3.5 is fixed.
tokio = { version = "0.2", features = ["full"] }